[package]
name = "cosmic-launcher-plugin-helper"
version = "0.1.0"
authors = ["Christoph Kröppl <ch.kroeppl@gmx.at>"]
license = "MIT"
edition = "2021"

description = "useful macros to support pop-launcher plugin development"
keywords = ["pop", "pop-os", "pop!_os", "launcher", "plugin", "launcher-toolkit", "macro"]
categories = ["development-tools"]

documentation = "https://docs.rs/cosmic-launcher-plugin-helper"
homepage = "https://github.com/nkia-christoph/cosmic-launcher-plugin-helper/tree/master/helper"
repository = "https://github.com/nkia-christoph/cosmic-launcher-plugin-helper"
readme = "../README.md"
publish = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
    "--cfg", "docsrs", "--html-before-content",
    "fix-docsrs-li-details-summary.html"
]

[lib]
name = "helper"

[features]
default = ["send", "dep:helper-macros"]
send = []
panic = ["send", "dep:helper-macros"]

[dependencies]

[dependencies.helper-macros]
package = "cosmic-launcher-plugin-helper-macros"
# version = "0.1.0"
path = "../helper_macros"
optional = true

[dev-dependencies]
pop-launcher-toolkit = { git = "https://github.com/pop-os/launcher/", tag = "1.2.7" }
tokio = { version = "1", features = ["rt"] }
tokio-test = { version = "^0.2.0" }

[badges]
maintenance = { status = "actively-developed" }

[lints.clippy]
pedantic = "warn"

[profile.dev]
split-debuginfo = "unpacked"
