[workspace]
resolver = "2"
members = [
    "helper",
    "helper_macros",
]

[patch.crates-io]
smithay-client-toolkit = { git = "https://github.com/smithay/client-toolkit", tag = "v0.20.0" }
# feature flag needed since 0.26.0
nix = { git = "https://github.com/nix-rust/nix.git", tag = "v0.26.4", features = ["fs"] }
